name: flugel-test

on: push

jobs:
  test:
    name: test terraform with terratest
    runs-on: ubuntu-latest
    #container: golang:1.16.5-alpine3.13 
    container: golang:1.15.13-alpine3.13

    steps:
    - uses: actions/checkout@v2
    - run: wget https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
    - run: unzip terraform_0.15.5_linux_amd64.zip && rm terraform_0.15.5_linux_amd64.zip
    - run: mv terraform /usr/bin/terraform
    - run: ls
    - run: echo ${{ github.repository }}
    - run: ls
    - run: cd test
    - run: go mod init github.com/noussydjimi/testflugel
    - run: go test -v test
    - run: cd .. 
    - run: cd test-instance
    - run: go mod init github.com/noussydjimi/testflugel
    - run: go test -v terra_test.go
